# -*- coding: utf-8 -*-
"""Iris flower classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18YxlkDfd-_bXktJ9Q8_n-lgzh8CPcWF_
"""

import pandas as pd

df = pd.read_csv("IRIS.csv")
df.head()

df.columns

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

X = df.drop('species', axis=1)
y = df['species']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

